### PR TITLE
Cubic Hermite interpolation

### PR DESCRIPTION
**Pull request by mateuszbaran**
I've made the first example. This repository didn't look particularly inviting being empty :slightly_smiling_face: .

### CODE REVIEW

**Comment by mateuszbaran** [comment]
@kellertuer Do you know why quarto can't find the Julia kernel here on CI?
```
ERROR: Jupyter kernel 'julia-1.10' not found. Known kernels: python3. Run 'quarto check jupyter' with your python environment activated to check python version used.
```
I've tried a few things from other repositories but nothing solved this.

**Comment by kellertuer** [comment]
I can check later today. Without checking it out – the error message reads like iJulia was not compiled in that env (maybe the wrong one was chosen?).

Yes that is why this is also not registered and such; I did not yet find time to move examples like the Bezier one here.

**Comment by mateuszbaran** [comment]
Thanks! I was working on https://github.com/JuliaManifolds/ManifoldDiffEq.jl/issues/8 and decided that, since I'm already investigating how it works, I could as well make an example out of it.

**Comment by kellertuer** [comment]
`make.jl` now correctly makes sure quarto can be run (IJulia is precompiled), but your example run on quarto currently misses PythonPlot.

Shall we maybe in general switch to using Makie? I was thinking about maybe removing the receipts from Manifolds soon-ish when we have a ManifoldsMakie-or-so package (I think I have nice sphere plots in Makie soon)

**Comment by kellertuer** [comment]
> Thanks! 

No problem currently the quarto setup is not that easy and here we still had a bit of an old style (without CondaPkg) – so I hope now that starts fine on CI as well (but will still fail on PythonPlot) – maybe check what is missing in the examples/ environment – or do your own in a subfolder for the example maybe (leave the notebook in the examples/ folder but internally activate the env from the subfolder)

**Comment by kellertuer** [comment]
One could of course argue whether this is a Manifolds example or a ManifoldDiff example. But maybe that is just a matter of perspective. If the “thing on the manifold” or the manifold itself is in the center, we could surely put it here.

**Comment by mateuszbaran** [comment]
> your example run on quarto currently misses PythonPlot.

That's very likely. I have issues running quarto on my PC (it usually freezes my entire desktop environment) so here I was just fixing errors as they appeared on CI.

> Shall we maybe in general switch to using Makie? I was thinking about maybe removing the receipts from Manifolds soon-ish when we have a ManifoldsMakie-or-so package (I think I have nice sphere plots in Makie soon)

I'm not sure. Plots.jl is nice because it's more snappy than Makie.jl (or at least it was the last time I checked). Makie on the other hand can make more fancy 3D visualizations. I'm fine with extending Makie support but maybe let's wait with removing Plots stuff until we see Makie works for us? We can use both in the meantime.

> One could of course argue whether this is a Manifolds example or a ManifoldDiff example. But maybe that is just a matter of perspective. If the “thing on the manifold” or the manifold itself is in the center, we could surely put it here.

Well, let's maybe not split "Examples" packages that much. This one can serve both Manifolds and ManifoldDiff.

**Comment by kellertuer** [comment]
Sure, we can also categorise the examples here at some point.

The thought mainly came from that we have `ManoptExamples` already – but we should not to a `XExamples` for every of our packages. So sure, let's keep them here and maybe do an advanced menu or an overview page when that becomes necessary

**Comment by mateuszbaran** [comment]
IIRC this is ready so maybe we could merge it?

**Review by kellertuer — COMMENTED** [review]
Ok, and then register a first version of this.

**Review by kellertuer — APPROVED** [review]

**Pull request merged**
